server:
  port: 7902
spring:
  application:
    name: provider-mockexam
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/center
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: 123
    timeout: 5000
    database: 0
    pool:
      max-active: 1000
      max-idle: 300
      min-idle: 100
      max-wait: -1
mybatis:
  typeAliasesPackage: com.ceac.easystudy
  mapperLocations: classpath:mappers/*.xml
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
eureka:
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
ribbon:
  eureka:
    enabled: true
logging:
  level:
    root: INFO
